CREATE TABLE CUSTOMER(
    Cust_name INT,
    Cust_street VARCHAR(20),
    Cust_city VARCHAR(20)
);

ALTER TABLE CUSTOMER ADD PRIMARY KEY(Cust_city);

INSERT INTO CUSTOMER(Cust_name,Cust_street,Cust_city) 
VALUES("1","Maruti Nagar","GNT"),
("2","Madhapur","HYD"),
("3","Patamata","VJA");

ALTER TABLE CUSTOMER ADD COLUMN SALARY INT DEFAULT 50000;
SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER CHANGE Cust_street Cust_town VARCHAR(20);
SELECT * FROM CUSTOMER;

ALTER TABLE CUSTOMER DROP COLUMN SALARY;
SELECT * FROM CUSTOMER;

DELETE FROM CUSTOMER WHERE Cust_city="HYD";
SELECT * FROM CUSTOMER;